---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-{{ .Release.Name }}-0
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.server.storage.capacity }}
  claimRef:
    kind: PersistentVolumeClaim
    name: data-{{ .Release.Name }}-0
    namespace: {{ .Release.Namespace }}
  gcePersistentDisk:
    fsType: ext4
    pdName: data-{{ .Release.Name }}-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - {{ .Values.google.region }}-a
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-{{ .Release.Name }}-1
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.server.storage.capacity }}
  claimRef:
    kind: PersistentVolumeClaim
    name: data-{{ .Release.Name }}-1
    namespace: {{ .Release.Namespace }}
  gcePersistentDisk:
    fsType: ext4
    pdName: data-{{ .Release.Name }}-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - {{ .Values.google.region }}-b
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-{{ .Release.Name }}-2
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.server.storage.capacity }}
  claimRef:
    kind: PersistentVolumeClaim
    name: data-{{ .Release.Name }}-2
    namespace: {{ .Release.Namespace }}
  gcePersistentDisk:
    fsType: ext4
    pdName: data-{{ .Release.Name }}-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/zone
              operator: In
              values:
                - {{ .Values.google.region }}-c
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  volumeMode: Filesystem
