apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: vault-pdb
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels: 
      {{- include "vault.selectorLabels" . | nindent 6 }}
