{{ template "vault.mode" . }}
{{- if ne .mode "external" }}
{{- if and (eq (.Values.global.enabled | toString) "true") (ne .mode "dev") -}}
{{ if or (.Values.server.standalone.config) (.Values.server.ha.config) -}}
apiVersion: v1
kind: Secret
metadata:
  name: vault-server-tls
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    component: server
type: Opaque
data:
  tls.ca: {{ .Values.server.tlsCA }}
  tls.crt: {{ .Values.server.tlsCrt }}
  tls.key: {{ .Values.server.tlsKey }}
{{- end }}
{{- end }}
{{- end }}
