---
apiVersion: v1
kind: Service
metadata:
  name: vault-active
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
    networking.gke.io/internal-load-balancer-allow-global-access: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.server.service.active.loadBalancerIP }}
  externalTrafficPolicy: Local
  publishNotReadyAddresses: false
  ports:
    - name: data
      port: 8200
      targetPort: 8200
  selector: 
    vault-active: "true"
    vault-sealed: "false"
    {{- include "vault.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: vault-standby
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: false
  ports:
    - name: data
      port: 8200
      targetPort: 8200
    - name: cluster
      port: 8201
      targetPort: 8201
  selector: 
    vault-active: "false"
    vault-sealed: "false"
    {{- include "vault.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: vault-cluster
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vault.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: data
      port: 8200
      targetPort: 8200
    - name: cluster
      port: 8201
      targetPort: 8201
  selector: 
    {{- include "vault.selectorLabels" . | nindent 4 }}
